### ISSUE TITLE
I receive server info but can't receive log

### ISSUE THREAD

**Issue by danieljsfernandes** [ScottKaye/CoreRCON#5] opened 2017-05-12 20:36 UTC
Hello,
I'm testing this library with your example (Program.cs) and i receive the number of players and info server but he never receive log from server like messages.
I can't get status responde to say hostname.

Am I doing something wrong?
Regards.

**Comment by ScottKaye** [comment] 2017-05-13 01:48
Hi Daniel,

I've only tested my library with TF2 servers, under the assumption that [the RCON protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol) wouldn't change much between games.  Unfortunately it seems that it does -- what game is your server running?

**Comment by danieljsfernandes** [comment] 2017-05-13 02:05
Hello,
My server run CS:GO. What should i change to it listen and get logs?
Regards

**Comment by ScottKaye** [comment] 2018-01-19 00:20
Closing as a duplicate of #3.  I haven't worked on this project in a very long time; hopefully you have found something better that works for you at this point!

**Closed as completed by ScottKaye** 2018-01-19 00:20 UTC
